name: workshop_mobi
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_nav_bar: ^5.0.6
  smooth_page_indicator: ^1.1.0
  flutter_signin_button: ^2.0.0
  qr_flutter: any
  cupertino_icons: ^1.0.2
  http: any
  get: ^4.6.6
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  fixnum: ^1.1.0
  dart_ipify: ^1.1.1
  material: ^1.0.0+2
  flutter_secure_storage: ^9.0.0
  lottie: ^2.7.0
  qr_code_scanner: any
  url_launcher: ^6.2.1
  google_fonts: any
  table_calendar: ^3.0.9
  google_sign_in: any
  flutter_facebook_auth: any
  oauth2: ^2.0.2
  webview_flutter: ^4.4.2
  provider: ^6.1.1
  flutter_inappwebview: ^5.8.0
  video_player: ^2.6.0
  chewie: ^1.0.0
  intl: ^0.18.1
  timeago: ^3.6.0
  change_app_package_name: ^1.1.0
  flutter_paypal_native: any
  curved_navigation_bar: ^1.0.3
  flutter_multi_select_items: ^0.4.2
  flutter_rating_bar: ^4.0.1
  
  image_picker: ^1.0.4
  firebase_storage: ^11.5.3
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.5
  firebase_app_check: ^0.2.1+8
  awesome_snackbar_content: ^0.1.3
  email_validator: ^2.1.17
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
